=== JorgeMoh/1DAM-LenguajeDeMarcas/Trabajo XML/Digipedia_XSD.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="digipedia">

        <xs:element name="digimon"  maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="familia" type="string" use="required"/>
                <xs:sequence>
                    <xs:element name="nombre" type="xs:string">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                            <xs:pattern value="^[A-Z][a-z]+(mon)$">
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="tipo" type="xs:string"/>
                    <xs:element name="nivel" type="xs:string" default="Infantil">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Infantil">
                                <xs:enumeration value="Adulto">
                                <xs:enumeration value="Perfecto">
                                <xs:enumeration value="Definitivo">
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:choice>
                        <xs:element name="virus"/>
                        <xs:element name="vacuna"/>
                    <xs:choice>
                <xs:sequence>
            </xs:complexType>
        </xs:element>

    </xs:element>
    
</xs:schema>

=== JorgeMoh/1DAM-LenguajeDeMarcas/Trabajo XML/DigiPedia.xml
<?xml version="1.0" encoding="UTF-8"?>

<digipedia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Digipedia_XSD.xsd">
    
    <!-- Esto es un digimon -->
    <digimon familia="Soldados de Pesdailla" >
        <nombre>Kerpymon</nombre>
        <tipo>Querubin</tipo>
        <nivel>Definitivo</nivel>
        </virus>
    </digimon>

    <digimon familia="Cazadores de Virus">
        <nombre>Kudamon</nombre>
        <tipo>Bestia Sagrada</tipo>
        <nivel>Infantil</nivel>
        </vacuna>
    </digimon>

</digipedia>

<!--
    <pokemon>
        <pokemon:nombre>Zoroark Hisui</pokemon:nombre>
        <pokemon:tipo>Fantasma</pokemon:tipo>
        <pokemon:tipo>Normal</pokemon:tipo>
        <habilidad>Ilusi√≥n</habilidad>
    </pokemon>
-->
